config/routes.rb
Rails.application.routes.draw do

  get 'public/sign_in'
  get 'public/home'
  get 'public/contact_us'
  get 'public/coming_soon'
  get 'public/doctors'
  get 'public/doctor_details'
  get 'zohoverify/verifyforzoho' => 'public#verifyforzoho'

  get 'public/search'
  post 'public/search_doctors'

  get 'public/open_appointment'
  post 'public/open_appointment'

  post 'public/login'

  get 'public/contact'
  get 'public/about'

  get 'public/doctor_registration'
  post 'public/register_doctor'
  
  post 'public/contact_form'
  post 'public/register_donor'
  post 'public/register_request_donation'
  post 'public/place_order'

  get 'public/privacy'
  get 'public/donor_registration'
  get 'public/request_donation'

  get 'public/healthy_living'
  get 'public/healthy_living/:id' => 'public#blog_details'

  get 'public/help'
  get 'public/show_location'
  get 'public/pharmacy'
  get 'public/add_medicine'
  get 'public/medicine_details'
  get 'public/checkout'

  get 'public/get_slots'

  get 'public/patient_registration'
  post 'public/register_patient'

  get 'public/appointment'
  post 'public/book_appointment'

  post 'public/search_medicine'

  get 'public/thank_you'

  get 'public/terms_and_conditions'

  get 'welcome/index'

  get 'welcome/about'
  get 'welcome/login'

  get 'welcome/help'

  get 'welcome/faqs'

  get 'welcome/contact_us'

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/help'

  get 'welcome/faqs'
  
  get 'api/get_patients'
  get 'api/get_appointments'
  get 'api/get_medicines'
  get 'api/get_orders'
  get 'api/get_stock'

  get 'api/verify_email'
  

  get 'admin' => "admins#dashboard"

  resources :pharmacies do
    collection do
      get 'login'
      get 'dashboard'
      get 'logout'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'orders'
      get 'set_status'

      get 'stock'
      get 'add_stock'
      post 'add_new_stock'
    end
  end

  resources :patients do 
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'appointments'
      get 'request_appointment'
      post 'create_new_appointment'

      get 'get_slots'

      get 'prescriptions'
      get 'prescription_details'
    end
  end

  resources :bloggers do
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'new_article'
      post 'create_new_article'
    end
  end

  resources :admins do 
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'procedures'
      get 'specialities'
      get 'conditions'
      get 'new_blood_group'
      get 'new_procedure'
      get 'new_condition'
      get 'destroy_session'
      get 'new_speciality'

      get 'hospitals'
      get 'cities'
      get 'new_hospital'
      get 'new_city'
      get 'donation_requests'
      get 'assign_donation_request'
      post 'assign_donor'

      get 'orders'
      get 'order_details'
      post 'assign_order'

      get 'new_blogger'
      post 'create_new_blogger'

      get 'medicines'
      get 'edit_medicine'
      get 'delete_medicine'
      post 'edit_medicine_data'

      get 'new_medicine'
      post 'create_new_medicine'
      get 'import_medicines'
      post 'import_medicines_data'

      get 'blogs'
      get 'publish_blog'
      get 'blog_content'

      post 'add_new_hospital'
      post 'add_new_city'
      post 'add_new_blood_group'
      post 'create_new_procedure'
      post 'create_new_speciality'
      post 'create_new_condition'
      post 'session_login'

      get 'edit_location'
      post 'edit_hospital_location'

      get 'pharmacies'

      get 'donors'
    end
  end

  resources :users do
     collection do
      get 'dashboard'
      post 'session_login'
    end
  end
  
resources :doctors do
     collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'create_appointment' 
      post 'session_login'
    end
    member do
      get 'patients'
      get 'appointments'
      get 'via_n_appointments'
      get 'new_appointment'
      get 'new_stub_appointment'
      post 'add_new_stub_appointment'

      get 'availability_settings'
      post 'set_availability_details'
      get 'get_slots'

      get 'procedures'
      get 'add_procedure'
      post 'add_new_procedure'

      get 'conditions'
      get 'new_condition'
      post 'add_new_condition'

      get 'specialities'
      get 'add_speciality'
      post 'add_new_speciality'

      get 'prescriptions'
      get 'new_prescription'
      post 'add_new_prescription'
      get 'prescription_details'

      get 'settings'
      post 'update_information'

      get 'change_picture'
      post 'add_new_picture'

      get 'accept_appointment'
      get 'reject_appointment'

      get 'mark_paid'
      post 'mark_appointment_paid'
    end
  end

  root 'public#healthy_living'

end

app/models/blogger.rb
class Blogger < ActiveRecord::Base
	has_many :articles

  def blocked?
    false
  end

end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
  before_action :authenticate_blogger, except: [:login ,:session_login]
  before_action :set_blogger, only: [:show, :edit, :update, :destroy]

  def new_article
    @article = Article.new
    @tags = ActsAsTaggableOn::Tag.all
  end

  def create_new_article
    @article = current_blogger.articles.create(title: params[:title], context: params[:content], state: 0)
    @article.documents.create(image: params[:image])
    for i in 0..params[:tags].size-1
      @article.tag_list.add(params[:tags][i])
    end
    @article.save
    flash[:success] = "Your article has been saved. It will be published shortly."
    redirect_to dashboard_bloggers_path(current_blogger)
    
  end

  def dashboard
    
  end

  def session_login
    @blogger = Blogger.find_by(email: params[:email])
      if @blogger.blank? 
         redirect_to({ :action=>'login' }, alert: 'Information you entered is wrong.') 
         return
      elsif @blogger.password != params[:password]
            redirect_to({ :action=>'login' }, alert: 'Information you entered is wrong.') 
         return
      elsif !@blogger.blocked?
      
        set_session @blogger
        redirect_to({ :action=>'dashboard' }, notice: 'Welcome to your dashboard.')
        return

     else
      redirect_to({ :action=>'login' }, alert: 'Information you entered is wrong.') 
      return 
     end
  end

  def logout
    reset_session
    redirect_to root_path
  end
  

  def destroy_session 
    reset_session 
    redirect_to login_bloggers_path
  end

  def set_session blogger
    session[:blogger] = blogger.id
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogger
      @blogger = blogger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogger_params
      params.permit(:name, :email, :username, :password)
    end

    def authenticate_blogger
     if session[:blogger].blank? && session[:admin].blank?
        redirect_to( login_bloggers_path, notice: 'Please login to conitnue.') 
     end
  end 
end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/views/bloggers/_blogger_login_form.html.erb
 <div class="app signin v2 usersession">
    <div class="session-wrapper">
    <div class="session-carousel slide" data-ride="carousel" data-interval="300">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active" style="background-image:url(/images/bg1.jpg);background-size:cover;background-repeat: no-repeat;background-position: 50% 50%;">
          <div class="item" style="background-image:url(/images/bg2.jpg);background-size:cover;background-repeat: no-repeat;background-position: 50% 50%;">
          </div>
        </div>
      </div>
            </div>
      <div class="card bg-white no-border">
        <div class="card-block">
           <%= form_tag session_login_bloggers_path, method: "POST" do %>
        
            <div class="text-center m-b">
              <h4 class="text-uppercase">Hello Mighty Blogger</h4>
              <p>Is this really you? Share some credentials dude</p>
            </div>
            <div class="form-inputs p-b">
             <div class="form-group m-b">
              <%= label_tag :email ,:email , class: "text-uppercase" %>
              <%= text_field_tag "email", "",autofocus: true, class: "form-control input-lg", placeholder: "What was your email again?", required: "" %>
              <div class="help-block with-errors"></div>
            </div>
             <div class="form-group m-b">
            <%= label_tag :password,:password, class: "text-uppercase" %>
            <%= password_field_tag "password", "", autocomplete: "off", class: "form-control  input-lg", placeholder: "Can't let you go with the password dude", "data-minlength" => "8" , required: ""  %>
            <div class="help-block with-errors"></div>
          </div>
          
          <div class="checkbox">
            <label>
              <%= check_box_tag :remember_me , false%> 
              Remember Me
            </label>
          </div>
                
            </div>
             <%= submit_tag "Log in", class: "btn btn-primary btn-block btn-lg m-b" %>
             <% end %>
        </div>
      </div>
      <div class="push"></div>
    </div>
  </div>

app/views/bloggers/_dashboard.html.erb
<!-- main area -->
       <div class="main-content">
        <div class="page-title">
          <div class="title">Dashboard</div>
        </div>    
        <% if flash[:success].present? %>
        <div class="alert alert-success">
          <strong>Success!</strong> <%= flash[:success] %>
        </div>
        <% end %>
        <div class="row">
          <div class="col-sm-3">
            <div class="card card-block bg-white">
              <h4 class="card-title">Articles</h4>
                <p class="card-text" id="teacher_box">
                <br/>
                Stats coming soon bro, chill!

              </p>    
            </div>
          </div>
        </div>
        
        
          
      <!-- /main area -->
      
  <div class="modal bs-modal-lg" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/bloggers/_footer.html.erb
 <!-- START FOOTER -->
        <div id="footer">
            <div class="container">
                <div class="row">
                    <div class="footer-widgets-area with-sidebar-right">
                        <div class="widget-first widget span2 widget_text"><h3>About Us</h3>
                            <div class="textwidget">
                               Easycare.pk is one of the emerging platforms for the individuals of health care industry to coactively
                               involve with their patients. The sole purpose of this platform is to make the lives of the people simpler and to serve the society in a unique way. EasyCare.pk is not only a concise but a modernized gateway for both the patients and the doctors to interact easily.
                            </div>
                        </div>

                        <div class="widget span2 widget_nav_menu">
                            <h3>More About Us</h3>

                            <div class="menu-widget-footer-container">
                                <ul id="menu-widget-footer" class="menu">
                                    <li class="menu-item menu-item-type-post_type menu-item-object-page">
                                        <a href="/public/about">About</a>
                                    </li> 

                                    <li class="menu-item menu-item-type-post_type menu-item-object-page">
                                        <a href="/public/privacy">Privacy Policy</a>
                                    </li>

                                    <li class="menu-item menu-item-type-post_type menu-item-object-page">
                                        <a href="/public/terms_and_conditions">Terms & Conditions</a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div class="widget-last widget span2 widget_nav_menu">
                            <h3>Socialize</h3>

                            <div class="menu-socialize-container">
                                <ul id="menu-socialize" class="menu">

                                    <li class="menu-item menu-item-type-custom">
                                        <a href="https://www.facebook.com/Easy-Care-1296524673695043">Facebook</a>
                                    </li>

                                    <li class="menu-item menu-item-type-custom">
                                        <a href="https://twitter.com/easycare_pk">Twitter</a>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>

                    <div id="contact" class="footer-widgets-sidebar with-sidebar-right">
                        <div  class="widget-first widget span6 yit_quick_contact">
                            <h3>Get in touch</h3>
                            <%= form_tag public_contact_form_path, method: :post ,class: "contact-form row" do %>

                                <div class="usermessagea"></div>
                                <fieldset>
                                    <ul>
                                        <li class="text-field with-icon span3">
                                            <label>
                                                <span class="mainlabel">Name</span>
                                            </label>

                                            <div class="input-prepend">
                                                <span class="add-on">
                                                    <img src="/users/images/footer/author-footer.png" alt="" title=""/></span>
                                                <input type="text" name="name" class="with-icon required" value=""/>
                                            </div>
                                            <div class="msg-error"></div>
                                            <div class="clear"></div>
                                        </li>

                                        <li class="text-field with-icon span3">
                                            <label>
                                                <span class="mainlabel">Email</span>
                                            </label>

                                            <div class="input-prepend">
                                                <span class="add-on">
                                                    <img src="/users/images/footer/envelope-footer.png" alt="" title=""/>
                                                </span>
                                                <input type="text" name="email" class="with-icon required email-validate" value=""/>
                                            </div>
                                            <div class="msg-error"></div>
                                            <div class="clear"></div>
                                        </li>

                                        <li class="textarea-field with-icon span6">
                                            <label>
                                                <span class="mainlabel">Message</span>
                                            </label>

                                            <div class="input-prepend">
                                                <span class="add-on">
                                                    <img src="/users/images/footer/pencil-footer.png" alt="" title=""/>
                                                </span>
                                                <textarea name="message" rows="8" cols="30" class="with-icon required"></textarea>
                                            </div>
                                            <div class="msg-error"></div>
                                            <div class="clear"></div>
                                        </li>

                                        <li class="submit-button span6">
                                            <div style="position:absolute;left:-9999px;">
                                                <input type="text" name="email_check_2" id="email_check_2" value=""/>
                                            </div>
                                            <input type="hidden" name="yit_action" value="sendemail" id="yit_action"/>
                                            <input type="hidden" name="yit_referer" value="index.html"/>
                                            <input type="hidden" name="id_form" value="228"/>
                                            <input type="submit" name="yit_sendemail" value="SEND" class="sendmail alignright"/>
                                            <div class="clear"></div>
                                        </li>
                                    </ul>
                                </fieldset>
                            <% end %>

                            <script type="text/javascript">
                                var messages_form_228 = {
                                    name: "Insert the name",
                                    email: "Insert a valid email",
                                    message: "Insert a message"
                                };
                            </script>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END FOOTER -->

        <!-- START COPYRIGHT -->
        <div id="copyright">
            <div class="container">
                <div class="row">
                    <div class="left span6">
                        <p>
                            &nbsp;Copyright 2012 - <strong>EasyCare.pk</strong> powered by
                            <a href="http://eunoia.tech">Eunoia</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <!-- END COPYRIGHT -->

        <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery("#contact_link").click(function() {
                    jQuery('html, body').animate({
                        scrollTop: jQuery("#contact").offset().top
                    }, 2000);
                });
        });
        </script>

app/views/bloggers/_head_menu.html.erb
<div class="app layout-fixed-header">
 <div class="sidebar-panel offscreen-left">
      <div class="brand">
        <!-- toggle offscreen menu -->
        <div class="toggle-offscreen">
          <a href="javascript:;" class="visible-xs hamburger-icon" data-toggle="offscreen" data-move="ltr">
            <span></span>
            <span></span>
            <span></span>
          </a>
        </div>
        <!-- /toggle offscreen menu -->
        <!-- logo -->
        <a class="brand-logo">
          <span>Blogging Engine</span>
        </a>
        <a href="#" class="small-menu-visible brand-logo">P</a>
        <!-- /logo -->
      </div>
      <ul class="quick-launch-apps hide">
        <li>
          <a href="apps-gallery.html">
            <span class="app-icon bg-danger text-white">
            G
            </span>
            <span class="app-title">Gallery</span>
          </a>
        </li>
        <li>
          <a href="apps-messages.html">
            <span class="app-icon bg-success text-white">
            M
            </span>
            <span class="app-title">Messages</span>
          </a>
        </li>
        <li>
          <a href="apps-social.html">
            <span class="app-icon bg-primary text-white">
            S
            </span>
            <span class="app-title">Social</span>
          </a>
        </li>
        <li>
          <a href="apps-travel.html">
            <span class="app-icon bg-info text-white">
            T
            </span>
            <span class="app-title">Travel</span>
          </a>
        </li>
      </ul>
      <!-- main navigation -->
      <nav role="navigation">
        
        <ul class="nav">
          <!-- dashboard --> 
          <li>
            <%= link_to dashboard_bloggers_path do %>
                <i class="fa fa-dashboard"></i>
                <span>Dashboard</span>
            <% end %>
          </li>
          <li>
            <%= link_to new_article_blogger_path(current_blogger) do %>
                <i class="fa fa-plus-square"></i>
                <span>New Article</span>
            <% end %>
          </li>

<!--           /dashboard -->
          <!-- cards -->
         
          <!-- /cards -->
        </ul>
      </nav>
      <!-- /main navigation -->
    </div>
    <!-- /sidebar panel -->
  <!-- content panel -->
    <div class="main-panel">
      <!-- top header -->
      <div class="header navbar">
        <div class="brand visible-xs">
          <!-- toggle offscreen menu -->
          <div class="toggle-offscreen">
            <a href="javascript:;" class="hamburger-icon visible-xs" data-toggle="offscreen" data-move="ltr">
              <span></span>
              <span></span>
              <span></span>
            </a>
          </div>
          <!-- /toggle offscreen menu -->
          <!-- logo -->
          <a class="brand-logo">
            <span>ELEA</span>
          </a>
          <!-- /logo -->
        </div>
        <ul class="nav navbar-nav hidden-xs">
          <li>
            <a href="javascript:;" class="small-sidebar-toggle ripple" data-toggle="layout-small-menu">
              <i class="icon-toggle-sidebar"></i>
            </a>
          </li>
         <!--  <li class="searchbox">
            <a href="javascript:;" data-toggle="search">
              <i class="search-close-icon icon-close hide"></i>
              <i class="search-open-icon icon-magnifier"></i>
            </a>
          </li> -->
          <li class="navbar-form search-form hide">
            <input type="search" class="form-control search-input" placeholder="Start typing...">
            
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right hidden-xs">
          <li>
            <a href="javascript:;" class="ripple" data-toggle="dropdown">
              <img src="/images/avatar.jpg" class="header-avatar img-circle" alt="user" title="user">
              <span>Blogger Jigger</span>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
             <li>
                <a href="/help" target="_blank">Help</a>
              </li>
              <li>
                <%= link_to "Logout", logout_bloggers_path, :method => :get %>              
              </li>
            </ul>
          </li>
          <li>
            <a href="javascript:;" class="ripple" data-toggle="layout-chat-open">
              <i class="icon-user"></i>
            </a>
          </li>
        </ul>
      </div>
      <!-- /top header -->
   

app/views/bloggers/_new_article_form.html.erb
<div class="main-content">
  <div class="page-title">
    <div class="title">Create Article</div>
  </div>
  <div class="card bg-white">
    <div class="card-header text-lg-center">
      Give birth to your baby!
    </div>
    <div class="card-block">
      <div class="row m-a-0">
        <div class="col-lg-12">
          <%= form_tag create_new_article_blogger_path(current_blogger), class:"form-horizontal", role: "form", method: :post, id:"form", "autocomplete" => "off", :multipart => true do %>
            <div class="form-group">
              <label class="col-sm-2 control-label">Title</label>
              <div class="col-sm-8">
                <%= text_field_tag :title, "", "placeholder" => "Enter a suitable title for your article", class: "form-control m-b" %> 
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Content</label>
              <div class="col-sm-8">
                <%= text_area_tag :content, "", "placeholder" => "Enter the content for your article", class: "form-control m-b", "rows" => "7" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Tags</label>
              <div class="col-sm-8">
                <%= select_tag "tags", options_from_collection_for_select(@tags, "name", "name"), class: "select-tags form-control", style: "width: 100%;", multiple: true %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Image</label>
              <div class="col-sm-8">
                <%= file_field_tag :image, class: "form-control m-b" %> 
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 text-lg-right">
                <%= submit_tag "Save",class:"btn btn-primary " %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bloggers/_top_bar.html.erb
  <div id="topbar">
            <div class="container">
                <div class="row">
                    <div id="nav" class="span12 light">

                        <!-- START MAIN NAVIGATION -->

                        <ul id="menu-menu" class="level-1">
                            <li>
                                <a href="<%= root_path %>">Home</a>
                                <!-- <ul class="sub-menu">
                                </ul> -->
                            </li>
                             <li>
                               <a href="<%= public_donor_registration_path %>">Register As Blood Donor</a>
                            </li>
                            <li>
                                <a href="<%= public_pharmacy_path %>">Pharmacy</a>
                                <!-- <ul class="sub-menu">
                                </ul> -->


                            </li>
                            <li>
                               <a href="<%= public_request_donation_path %>">Request Donation</a>
                            </li>
                            <li>
                                <a href="<%= public_about_path %>">About Us</a>
                                <!-- <ul class="sub-menu">
                                </ul> -->
                            </li>
                            <li>
                                <a href="#contact" id="contact_link">Contact Us</a>
                                <!-- <ul class="sub-menu">
                                </ul> -->
                            </li>
                            <li>
                                <a href="<%= destroy_session_bloggers_path %>" >Logout</a>
                                <!-- <ul class="sub-menu">
                                </ul> -->
                            </li>
                            

                        </ul>
                        <!-- END MAIN NAVIGATION -->

                        <!-- START TOPBAR LOGIN -->

                        <div id="topbar_login" class="not_logged_in">

                            <a class="topbar_login" href="#">
                                LOGIN <span class="sf-sub-indicator"></span>
                            </a>

                            <div id="fast-login" class="access-info-box">
                                <form action="#" method="post" name="loginform">

                                    <div class="form">
                                        <p>
                                            <label>
                                                Username<br/>
                                                <input type="text" tabindex="10" size="20" value="" name="log" class="input-text" />
                                            </label>
                                        </p>

                                        <p>
                                            <label>
                                                Password<br/>
                                                <input type="password" tabindex="20" size="20" value="" name="pwd" class="input-text" />
                                            </label>
                                        </p>

                                        <a class="align-left lostpassword" href="#" title="Password Lost and Found">
                                            lost password?
                                        </a>

                                        <p class="align-right">
                                            <input type="submit" tabindex="100" value="Login" name="wp-submit" class="input-submit" />
                                            <input type="hidden" value="index.html" name="redirect_to" />
                                            <input type="hidden" value="1" name="testcookie" />
                                        </p>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!-- END TOPBAR LOGIN -->
                    </div>
                </div>
            </div>
        </div>

app/views/bloggers/dashboard.html.erb
<% content_for :head do %>
  <%= render 'shared/header' %>
<% end %>
<%= render 'head_menu' %>

<%= render 'dashboard' %>

<%= render 'shared/footer' %>

app/views/bloggers/login.html.erb
<!DOCTYPE html>
<html lang="en">
<% content_for :head do %>
 <meta charset="utf-8">
  <title>Blog your life out</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
  <!-- build:css({.tmp,app}) styles/app.min.css -->
  <link rel="stylesheet" href="/styles/webfont.css">
  <link rel="stylesheet" href="/styles/climacons-font.css">
  <link rel="stylesheet" href="/vendor/bootstrap/dist/css/bootstrap.css">
  <link rel="stylesheet" href="/styles/font-awesome.css">
  <link rel="stylesheet" href="/styles/card.css">
  <link rel="stylesheet" href="/styles/sli.css">
  <link rel="stylesheet" href="/styles/animate.css">
  <link rel="stylesheet" href="/styles/app.css">
  <link rel="stylesheet" href="/styles/app.skins.css">
  <!-- endbuild -->
<% end %>
 
<%= render 'blogger_login_form' %>
    
<% content_for :foot do %>
 <!-- build:js({.tmp,app}) scripts/app.min.js -->
  <script src="/scripts/helpers/modernizr.js"></script>
  <script src="/vendor/jquery/dist/jquery.js"></script>
  <script src="/vendor/bootstrap/dist/js/bootstrap.js"></script>
  <script src="/vendor/fastclick/lib/fastclick.js"></script>
  <script src="/vendor/perfect-scrollbar/js/perfect-scrollbar.jquery.js"></script>
  <script src="/scripts/helpers/smartresize.js"></script>
  <script src="/scripts/constants.js"></script>
  <script src="/scripts/main.js"></script>
  <script src="/scripts/validator.min.js"></script>
  <!-- endbuild -->
   <script src="/vendor/jquery-validation/dist/jquery.validate.min.js"></script>
  <!-- end page scripts -->
  <!-- initialize page scripts -->
  <script type="text/javascript">
    $('#form').validator();
  </script>
  <!-- end initialize page scripts -->
<% end %>