config/routes.rb
Rails.application.routes.draw do

  get 'public/sign_in'
  get 'public/home'
  get 'public/contact_us'
  get 'public/coming_soon'
  get 'public/doctors'
  get 'public/doctor_details'
  get 'zohoverify/verifyforzoho' => 'public#verifyforzoho'

  get 'public/search'
  post 'public/search_doctors'

  get 'public/open_appointment'
  post 'public/open_appointment'

  post 'public/login'

  get 'public/contact'
  get 'public/about'

  get 'public/doctor_registration'
  post 'public/register_doctor'
  
  post 'public/contact_form'
  post 'public/register_donor'
  post 'public/register_request_donation'
  post 'public/place_order'

  get 'public/privacy'
  get 'public/donor_registration'
  get 'public/request_donation'

  get 'public/healthy_living'
  get 'public/healthy_living/:id' => 'public#blog_details'

  get 'public/help'
  get 'public/show_location'
  get 'public/pharmacy'
  get 'public/add_medicine'
  get 'public/medicine_details'
  get 'public/checkout'

  get 'public/get_slots'

  get 'public/patient_registration'
  post 'public/register_patient'

  get 'public/appointment'
  post 'public/book_appointment'

  post 'public/search_medicine'

  get 'public/thank_you'

  get 'public/terms_and_conditions'

  get 'welcome/index'

  get 'welcome/about'
  get 'welcome/login'

  get 'welcome/help'

  get 'welcome/faqs'

  get 'welcome/contact_us'

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/help'

  get 'welcome/faqs'
  
  get 'api/get_patients'
  get 'api/get_appointments'
  get 'api/get_medicines'
  get 'api/get_orders'
  get 'api/get_stock'

  get 'api/verify_email'
  

  get 'admin' => "admins#dashboard"

  resources :pharmacies do
    collection do
      get 'login'
      get 'dashboard'
      get 'logout'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'orders'
      get 'set_status'

      get 'stock'
      get 'add_stock'
      post 'add_new_stock'
    end
  end

  resources :patients do 
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'appointments'
      get 'request_appointment'
      post 'create_new_appointment'

      get 'get_slots'

      get 'prescriptions'
      get 'prescription_details'
    end
  end

  resources :bloggers do
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'new_article'
      post 'create_new_article'
    end
  end

  resources :admins do 
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'procedures'
      get 'specialities'
      get 'conditions'
      get 'new_blood_group'
      get 'new_procedure'
      get 'new_condition'
      get 'destroy_session'
      get 'new_speciality'

      get 'hospitals'
      get 'cities'
      get 'new_hospital'
      get 'new_city'
      get 'donation_requests'
      get 'assign_donation_request'
      post 'assign_donor'

      get 'orders'
      get 'order_details'
      post 'assign_order'

      get 'new_blogger'
      post 'create_new_blogger'

      get 'medicines'
      get 'edit_medicine'
      get 'delete_medicine'
      post 'edit_medicine_data'

      get 'new_medicine'
      post 'create_new_medicine'
      get 'import_medicines'
      post 'import_medicines_data'

      get 'blogs'
      get 'publish_blog'
      get 'blog_content'

      post 'add_new_hospital'
      post 'add_new_city'
      post 'add_new_blood_group'
      post 'create_new_procedure'
      post 'create_new_speciality'
      post 'create_new_condition'
      post 'session_login'

      get 'edit_location'
      post 'edit_hospital_location'

      get 'pharmacies'

      get 'donors'
    end
  end

  resources :users do
     collection do
      get 'dashboard'
      post 'session_login'
    end
  end
  
resources :doctors do
     collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'create_appointment' 
      post 'session_login'
    end
    member do
      get 'patients'
      get 'appointments'
      get 'via_n_appointments'
      get 'new_appointment'
      get 'new_stub_appointment'
      post 'add_new_stub_appointment'

      get 'availability_settings'
      post 'set_availability_details'
      get 'get_slots'

      get 'procedures'
      get 'add_procedure'
      post 'add_new_procedure'

      get 'conditions'
      get 'new_condition'
      post 'add_new_condition'

      get 'specialities'
      get 'add_speciality'
      post 'add_new_speciality'

      get 'prescriptions'
      get 'new_prescription'
      post 'add_new_prescription'
      get 'prescription_details'

      get 'settings'
      post 'update_information'

      get 'change_picture'
      post 'add_new_picture'

      get 'accept_appointment'
      get 'reject_appointment'

      get 'mark_paid'
      post 'mark_appointment_paid'
    end
  end

  root 'public#healthy_living'

end

app/models/pharmacy.rb
class Pharmacy < ActiveRecord::Base
	has_many :orders
	has_many :stocks

  def blocked?
    false
  end
end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  before_action :authenticate_pharmacy, except: [:login ,:session_login]
  before_action :set_pharmacy, only: [:show, :edit, :update, :destroy]


  def stock

  end

  def add_stock
    @medicines = Medicine.all
    respond_to do |format|
         format.js 
    end
  end

  def add_new_stock
    stock = Stock.where(medicine_id: params[:medicine_id], pharmacy_id: current_pharmacy.id)
    if stock.present?
      quantity = stock.first.amount + params[:quantity].to_i
      Stock.update(stock.first.id, amount: quantity)
    else
      Stock.create(pharmacy_id: current_pharmacy.id, medicine_id: params[:medicine_id], amount: params[:quantity])
    end
    flash[:success] = "Stock added successfully"
    redirect_to :back
  end


  def index
    @pharmacy = Pharmacy.all
  end

  # GET /pharmacies/1
  def show
  end
  
  def login
  end

  def logout
    reset_session
    redirect_to root_path
  end
  

  # GET /pharmacies/new
  def new
    @pharmacy = Pharmacy.new
  end

  # GET /pharmacies/1/edit
  def edit
  end

  # POST /pharmacies
  
  def create 
    @pharmacy = Pharmacy.create(name: params[:name], email: params[:email], username: params[:username], password: params[:password], lat: params[:lat], long: params[:long], address: params[:address])
    redirect_to :back
  end
 
  # PATCH/PUT /pharmacies/1
  def update
    respond_to do |format|
      if @pharmacy.update(pharmacy_params)
        format.html { redirect_to @doctor, notice: 'Pharmacy was successfully updated.' }
        format.json { render :show, status: :ok, location: @pharmacy }
      else
        format.html { render :edit }
        format.json { render json: @pharmacy.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_status
    Order.update(params[:order_id], :status => ORDER_STATUS[:delivered])
    redirect_to :back
  end

  # DELETE /pharmacies/1
  def destroy
    @pharmacy.destroy
    respond_to do |format|
      format.html { redirect_to pharmacy_url, notice: 'Pharmacy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   # newly added functions
  def session_login
    @pharmacy = Pharmacy.find_by(email: params[:email])
      if @pharmacy.blank? 
         redirect_to({ :action=>'login' }, alert: 'Information you entered is wrong.') 
         return
      elsif @pharmacy.password != params[:password]
            redirect_to({ :action=>'login' }, alert: 'Information you entered is wrong.') 
         return
      elsif !@pharmacy.blocked?
      
        set_session @pharmacy
        redirect_to({ :action=>'dashboard' }, notice: 'Welcome to your dashboard.')
        return

     else
      redirect_to({ :action=>'login' }, alert: 'Information you entered is wrong.') 
      return 
     end
  end

    def destroy_session 
      reset_session 
      redirect_to login_pharmacies_path
    end

    def set_session logger
     session[:pharmacy] = logger.id
    end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pharmacy
      @pharmacy = Pharmacy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.

    def authenticate_pharmacy
      
     if session[:pharmacy].blank? && session[:admin].blank?
        redirect_to( login_pharmacies_path, notice: 'Please login to conitnue.') 
     end
  end  
end

app/helpers/pharmacy_helper.rb
module PharmacyHelper
end

app/views/pharmacies/_add_stock_form.html.erb
<%= form_tag add_new_stock_pharmacy_path(current_pharmacy), role: "form", method: :post, id:"form", :multipart => true do %>
	<div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" onclick="$('.bs-modal-lg').popup('hide');" aria-hidden="true">×</button>
          <h4 class="modal-title">Add Stock</h4>
        </div>
        <div class="modal-body">
          <div class="container">
            <div class="row">
               <div class="form-group">
                <div class="row">
                  <div class="form-group">
                    <div class="row">
                      <label  class="col-sm-2 control-label">Select Medicine</label>
                      <div class="col-sm-3">
                      <select class="js-example-basic-single" name="medicine_id">
                        <% @medicines.each do |medicine| %>
                          <option value="<%= medicine.id %>"><%= medicine.name %> - Rs <%= medicine.price %></option>
                        <% end %>
                      </select>
                    </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="row">
                     <label  class="col-sm-2 control-label">Add Quantity</label>
                        <div class="col-sm-3">
                          <%= text_field_tag :quantity, "", class:"form-control m-b" %>
                        </div>
                    </div>
                  </div>                                   
            </div>
          </div>
        </div>
        </div>
    </div>
        <div class="modal-footer no-border">
        <button type="button" class="btn btn-default" data-dismiss="modal" onclick="$('.bs-modal-lg').popup('hide');">Close</button>
         <%= submit_tag "Submit", class:"btn btn-primary" %>
        </div>
      
<% end %>
<script type="text/javascript">
$(document).ready(function() {
  $(".js-example-basic-single").select2();
});
</script>

app/views/pharmacies/_dashboard.html.erb
<!-- main area -->
       <div class="main-content">
        <div class="page-title">
          <div class="title">Dashboard</div>
        </div>    
        <div class="row">
          <div class="col-sm-6">
            <div class="card card-block bg-white">
              <h4 class="card-title">Medicines</h4>
                <p class="card-text" id="teacher_box">
                <br/>
                

              </p>    
            </div>
          </div>
        </div>
          
      <!-- /main area -->
      
  <div class="modal bs-modal-lg" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/pharmacies/_foot.html.erb
<%= yield :foot %>
<% content_for :foot do %> 


<script src="/scripts/select2.min.js"></script>

<% end %>

app/views/pharmacies/_head_menu.html.erb
<div class="app layout-fixed-header">
 <div class="sidebar-panel offscreen-left">
      <div class="brand">
        <!-- toggle offscreen menu -->
        <div class="toggle-offscreen">
          <a href="javascript:;" class="visible-xs hamburger-icon" data-toggle="offscreen" data-move="ltr">
            <span></span>
            <span></span>
            <span></span>
          </a>
        </div>
        <!-- /toggle offscreen menu -->
        <!-- logo -->
        <a class="brand-logo">
          <span>Pharmacy</span>
        </a>
        <a href="#" class="small-menu-visible brand-logo">P</a>
        <!-- /logo -->
      </div>
      <ul class="quick-launch-apps hide">
        <li>
          <a href="apps-gallery.html">
            <span class="app-icon bg-danger text-white">
            G
            </span>
            <span class="app-title">Gallery</span>
          </a>
        </li>
        <li>
          <a href="apps-messages.html">
            <span class="app-icon bg-success text-white">
            M
            </span>
            <span class="app-title">Messages</span>
          </a>
        </li>
        <li>
          <a href="apps-social.html">
            <span class="app-icon bg-primary text-white">
            S
            </span>
            <span class="app-title">Social</span>
          </a>
        </li>
        <li>
          <a href="apps-travel.html">
            <span class="app-icon bg-info text-white">
            T
            </span>
            <span class="app-title">Travel</span>
          </a>
        </li>
      </ul>
      <!-- main navigation -->
      <nav role="navigation">
        
        <ul class="nav">
          <!-- dashboard --> 
          <li>
            <%= link_to dashboard_pharmacies_path do %>
                <i class="fa fa-dashboard"></i>
                <span>Dashboard</span>
            <% end %>
          </li>
          <li>
            <%= link_to orders_pharmacy_path(current_pharmacy) do %>
                <i class="fa fa-table"></i>
                <span>Orders</span>
            <% end %>
          </li>
          <li>
            <%= link_to stock_pharmacy_path(current_pharmacy) do %>
                <i class="fa fa-table"></i>
                <span>Medicine Stock</span>
            <% end %>
          </li>
<!--           /dashboard -->
          <!-- cards -->
         
          <!-- /cards -->
        </ul>
      </nav>
      <!-- /main navigation -->
    </div>
    <!-- /sidebar panel -->
  <!-- content panel -->
    <div class="main-panel">
      <!-- top header -->
      <div class="header navbar">
        <div class="brand visible-xs">
          <!-- toggle offscreen menu -->
          <div class="toggle-offscreen">
            <a href="javascript:;" class="hamburger-icon visible-xs" data-toggle="offscreen" data-move="ltr">
              <span></span>
              <span></span>
              <span></span>
            </a>
          </div>
          <!-- /toggle offscreen menu -->
          <!-- logo -->
          <a class="brand-logo">
            <span>ELEA</span>
          </a>
          <!-- /logo -->
        </div>
        <ul class="nav navbar-nav hidden-xs">
          <li>
            <a href="javascript:;" class="small-sidebar-toggle ripple" data-toggle="layout-small-menu">
              <i class="icon-toggle-sidebar"></i>
            </a>
          </li>
         <!--  <li class="searchbox">
            <a href="javascript:;" data-toggle="search">
              <i class="search-close-icon icon-close hide"></i>
              <i class="search-open-icon icon-magnifier"></i>
            </a>
          </li> -->
          <li class="navbar-form search-form hide">
            <input type="search" class="form-control search-input" placeholder="Start typing...">
            
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right hidden-xs">
          <li>
            <a href="javascript:;" class="ripple" data-toggle="dropdown">
              <img src="/images/avatar.jpg" class="header-avatar img-circle" alt="user" title="user">
              <span><%= current_pharmacy.name %></span>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
             <li>
                <a href="/help" target="_blank">Help</a>
              </li>
              <li>
                <%= link_to "Logout", pharmacies_home_path, :method => :get %>              
              </li>
            </ul>
          </li>
          <li>
            <a href="javascript:;" class="ripple" data-toggle="layout-chat-open">
              <i class="icon-user"></i>
            </a>
          </li>
        </ul>
      </div>
      <!-- /top header -->
   

app/views/pharmacies/_medicine_form.html.erb
<%= form_tag create_new_medicine_pharmacy_path(current_pharmacy)  ,role: "form",method: :post, id:"form", :multipart => true do %>
           <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">New Medicine</h4>
        </div>
        <div class="modal-body">
          <div class="container">
            <div class="row">
               <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :name, "", class: "form-control m-b" %> 
                    </div>
                </div>
              </div>      
               <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Price</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :price, "", class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-3">
                      <%= text_area_tag :description, "", class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Image</label>
                    <div class="col-sm-3">
                      <%= file_field_tag :image, class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
                        
            </div>
          </div>
        </div>
        <div class="modal-footer no-border">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         <%= submit_tag "Submit",class:"btn btn-primary " %>
        </div>
      </div>
    </div>
          
          
<% end %>

app/views/pharmacies/_medicines_data_table.html.erb
<%= content_for :head do %>
  <link rel="stylesheet" href="/vendor/datatables/media/css/jquery.dataTables.css">
  <link rel="stylesheet" href="/vendor/sweetalert/dist/sweetalert.css">
<% end %>

<div class="card bg-white">
          <div class="card-header">
            Medicines
          </div>
          <div class="card-block">
            <table class="table table-bordered table-striped datatable editable-datatable responsive align-middle bordered">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Price</th>
                  <th>Description</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
        <input type="text" hidden="true" id="pharmacy_id" value="<%= current_pharmacy.id %>" />

<%= content_for :foot do %>

<!-- page scripts -->
<script src="/vendor/datatables/media/js/jquery.dataTables.js"></script>
<script src="/vendor/sweetalert/dist/sweetalert.min.js"></script>
<!-- end page scripts -->
<!-- initialize page scripts -->
<script src="/scripts/helpers/bootstrap-datatables.js"></script>
<script src="/scripts/tables/medicines-table-edit.js"></script>
<!-- end initialize page scripts -->
<% end %>     

<div class="modal bs-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
   
   
  </div>
  <%= link_to new_medicine_pharmacy_path(current_pharmacy), class: "fixed-new-button btn btn-info ", "data-toggle" =>"modal",  "data-target" => ".bs-modal-lg", remote: true do %>
    <i class="fa fa-plus"></i>
  <% end %>

app/views/pharmacies/_orders_data_table.html.erb
<%= content_for :head do %>
  <link rel="stylesheet" href="/vendor/datatables/media/css/jquery.dataTables.css">
  <link rel="stylesheet" href="/vendor/sweetalert/dist/sweetalert.css">
<% end %>

<div class="card bg-white">
          <div class="card-header">
            Orders
          </div>
          <div class="card-block">
            <table class="table table-bordered table-striped datatable editable-datatable responsive align-middle bordered">
              <thead>
                <tr>
                  <th>Order Id</th>
                  <th>Area</th>
                  <th>Charges</th>
                  <th>Address</th>
                  <th>Payment Method</th>
                  <th>Status</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>

<%= content_for :foot do %>

<!-- page scripts -->
<script src="/vendor/datatables/media/js/jquery.dataTables.js"></script>
<script src="/vendor/sweetalert/dist/sweetalert.min.js"></script>
<!-- end page scripts -->
<!-- initialize page scripts -->
<script src="/scripts/helpers/bootstrap-datatables.js"></script>
<script src="/scripts/tables/orders-table-edit.js"></script>
<!-- end initialize page scripts -->
<% end %>     

<div class="modal bs-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
   
   
  </div>
  

app/views/pharmacies/_stock_data_table.html.erb
<%= content_for :head do %>
  <link rel="stylesheet" href="/vendor/datatables/media/css/jquery.dataTables.css">
  <link rel="stylesheet" href="/vendor/sweetalert/dist/sweetalert.css">
<% end %>

<div class="card bg-white">
          <div class="card-header">
            Stock
          </div>
          <div class="card-block">
            <table class="table table-bordered table-striped datatable editable-datatable responsive align-middle bordered">
              <thead>
                <tr>
                  <th>Medicine Name</th>
                  <th>Price</th>
                  <th>Description</th>
                  <th>Quantity</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>

<%= content_for :foot do %>

<!-- page scripts -->
<script src="/vendor/datatables/media/js/jquery.dataTables.js"></script>
<script src="/vendor/sweetalert/dist/sweetalert.min.js"></script>
<!-- end page scripts -->
<!-- initialize page scripts -->
<script src="/scripts/helpers/bootstrap-datatables.js"></script>
<script src="/scripts/tables/stock-table-edit.js"></script>
<!-- end initialize page scripts -->
<% end %>     

<div class="modal bs-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
  </div>
  

app/views/pharmacies/dashboard.html.erb
<% content_for :head do %>
  <%= render 'shared/header' %>
<% end %>
<%= render 'head_menu' %>

<%= render 'dashboard' %>

<%= render 'shared/footer' %>

app/views/pharmacies/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/pharmacies/edit_medicine.js.erb
$(".bs-modal-lg").html("<%= escape_javascript(render(partial: "medicine_edit_form")) %>");
  $(".bs-modal-lg").modal('show');

app/views/pharmacies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Date of birth</th>
      <th>Email</th>
      <th>Username</th>
      <th>Password</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.gender %></td>
        <td><%= doctor.date_of_birth %></td>
        <td><%= doctor.email %></td>
        <td><%= doctor.username %></td>
        <td><%= doctor.password %></td>
        <td><%= doctor.phone %></td>
        <td><%= doctor.address %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/pharmacies/medicines.html.erb
<% content_for :head do %>
  <%= render 'shared/header' %>
<% end %>
  <%= render 'head_menu' %>

 <div class="main-content">
        <div class="page-title">
          <div class="title">Medicines</div>
          <div class="sub-title">All Medicines stored in the database</div>
        </div>    
        <%= render 'medicines_data_table' %>
      </div>

<%= render 'shared/footer' %>
<%= hidden_field_tag 'medicines_path', '/api/get_medicines'%>

app/views/pharmacies/new.js.erb
$(".bs-modal-lg").html("<%= escape_javascript(render(partial: "form")) %>");
  $(".bs-modal-lg").modal('show');
(function () {
// trim polyfill : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim
if (!String.prototype.trim) {
(function () {
  // Make sure we trim BOM and NBSP
  var rtrim = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;
  String.prototype.trim = function () {
    return this.replace(rtrim, '');
  };
})();
}
[].slice.call(document.querySelectorAll('input.input__field')).forEach(function (inputEl) {
// in case the input is already filled..
if (inputEl.value.trim() !== '') {
  classie.add(inputEl.parentNode, 'input--filled');
}
// events:
inputEl.addEventListener('focus', onInputFocus);
inputEl.addEventListener('blur', onInputBlur);
});

function onInputFocus(ev) {
classie.add(ev.target.parentNode, 'input--filled');
}

function onInputBlur(ev) {
if (ev.target.value.trim() === '') {
  classie.remove(ev.target.parentNode, 'input--filled');
}
}
})();
initPopups();

$("#new_student").validator().on('submit', function (e) {
  if (e.isDefaultPrevented()) {
  $("#form-error").html("Please Check Highlighted Fields");
    return false;
  } 
  else {
    return check();
  }
});