config/routes.rb
Rails.application.routes.draw do

  get 'public/sign_in'
  get 'public/home'
  get 'public/contact_us'
  get 'public/coming_soon'
  get 'public/doctors'
  get 'public/doctor_details'
  get 'zohoverify/verifyforzoho' => 'public#verifyforzoho'

  get 'public/search'
  post 'public/search_doctors'

  get 'public/open_appointment'
  post 'public/open_appointment'

  post 'public/login'

  get 'public/contact'
  get 'public/about'

  get 'public/doctor_registration'
  post 'public/register_doctor'
  
  post 'public/contact_form'
  post 'public/register_donor'
  post 'public/register_request_donation'
  post 'public/place_order'

  get 'public/privacy'
  get 'public/donor_registration'
  get 'public/request_donation'

  get 'public/healthy_living'
  get 'public/healthy_living/:id' => 'public#blog_details'

  get 'public/help'
  get 'public/show_location'
  get 'public/pharmacy'
  get 'public/add_medicine'
  get 'public/medicine_details'
  get 'public/checkout'

  get 'public/get_slots'

  get 'public/patient_registration'
  post 'public/register_patient'

  get 'public/appointment'
  post 'public/book_appointment'

  post 'public/search_medicine'

  get 'public/thank_you'

  get 'public/terms_and_conditions'

  get 'welcome/index'

  get 'welcome/about'
  get 'welcome/login'

  get 'welcome/help'

  get 'welcome/faqs'

  get 'welcome/contact_us'

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/help'

  get 'welcome/faqs'
  
  get 'api/get_patients'
  get 'api/get_appointments'
  get 'api/get_medicines'
  get 'api/get_orders'
  get 'api/get_stock'

  get 'api/verify_email'
  

  get 'admin' => "admins#dashboard"

  resources :pharmacies do
    collection do
      get 'login'
      get 'dashboard'
      get 'logout'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'orders'
      get 'set_status'

      get 'stock'
      get 'add_stock'
      post 'add_new_stock'
    end
  end

  resources :patients do 
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'appointments'
      get 'request_appointment'
      post 'create_new_appointment'

      get 'get_slots'

      get 'prescriptions'
      get 'prescription_details'
    end
  end

  resources :bloggers do
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'new_article'
      post 'create_new_article'
    end
  end

  resources :admins do 
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'procedures'
      get 'specialities'
      get 'conditions'
      get 'new_blood_group'
      get 'new_procedure'
      get 'new_condition'
      get 'destroy_session'
      get 'new_speciality'

      get 'hospitals'
      get 'cities'
      get 'new_hospital'
      get 'new_city'
      get 'donation_requests'
      get 'assign_donation_request'
      post 'assign_donor'

      get 'orders'
      get 'order_details'
      post 'assign_order'

      get 'new_blogger'
      post 'create_new_blogger'

      get 'medicines'
      get 'edit_medicine'
      get 'delete_medicine'
      post 'edit_medicine_data'

      get 'new_medicine'
      post 'create_new_medicine'
      get 'import_medicines'
      post 'import_medicines_data'

      get 'blogs'
      get 'publish_blog'
      get 'blog_content'

      post 'add_new_hospital'
      post 'add_new_city'
      post 'add_new_blood_group'
      post 'create_new_procedure'
      post 'create_new_speciality'
      post 'create_new_condition'
      post 'session_login'

      get 'edit_location'
      post 'edit_hospital_location'

      get 'pharmacies'

      get 'donors'
    end
  end

  resources :users do
     collection do
      get 'dashboard'
      post 'session_login'
    end
  end
  
resources :doctors do
     collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'create_appointment' 
      post 'session_login'
    end
    member do
      get 'patients'
      get 'appointments'
      get 'via_n_appointments'
      get 'new_appointment'
      get 'new_stub_appointment'
      post 'add_new_stub_appointment'

      get 'availability_settings'
      post 'set_availability_details'
      get 'get_slots'

      get 'procedures'
      get 'add_procedure'
      post 'add_new_procedure'

      get 'conditions'
      get 'new_condition'
      post 'add_new_condition'

      get 'specialities'
      get 'add_speciality'
      post 'add_new_speciality'

      get 'prescriptions'
      get 'new_prescription'
      post 'add_new_prescription'
      get 'prescription_details'

      get 'settings'
      post 'update_information'

      get 'change_picture'
      post 'add_new_picture'

      get 'accept_appointment'
      get 'reject_appointment'

      get 'mark_paid'
      post 'mark_appointment_paid'
    end
  end

  root 'public#healthy_living'

end

app/views/admins/_blogger_form.html.erb
<%= form_tag create_new_blogger_admins_path  ,role: "form",method: :post, id:"form", :multipart => true do %>
           <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">New Blogger</h4>
        </div>
        <div class="modal-body">
          <div class="container">
            <div class="row">
               <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :name, "", class: "form-control m-b" %> 
                    </div>
                </div>
              </div>      
              <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Username</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :username, "", class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
               <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :email, "", class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Password</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :password, "", class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
                        
            </div>
          </div>
        </div>
        <div class="modal-footer no-border">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         <%= submit_tag "Submit",class:"btn btn-primary " %>
        </div>
      </div>
    </div>
          
          
<% end %>

app/views/admins/_blogs_table.html.erb
<div class="card bg-white">
  <div class="card-header">
    Blogs
  </div>
  <% if flash[:success].present? %>
        <div class="alert alert-success">
          <strong>Success!</strong> <%= flash[:success] %>
        </div>
        <% end %>
  <div class="card-block">
    <table class="table table-bordered table-striped datatable editable-datatable responsive align-middle bordered">
      <thead>
        <tr>
          <th>Blogger ID</th>
          <th>Blog Title</th>
          <th>Blog Content</th>
          <th>Created At</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
      <% @blogs.each do |blog| %>
      <tr>
        <td>
          <%= blog.blogger_id %>
        </td>
        <td>
          <%= blog.title %>
        </td>
        <td>
          <%= link_to blog_content_admins_path(blog_id: blog.id), class: "btn btn-info", remote: true do %>
                <i class="fa fa-eye"></i>
              <span>Show Content</span>
            <% end %>
        </td>
        <td>
          <%= blog.created_at %>
        </td>
        <td>
          <% if blog.state == 0  || blog.state == nil %>
            <%= link_to publish_blog_admins_path(blog_id: blog.id), class: "btn btn-primary" do %>
                <i class="fa fa-eye"></i>
              <span>Click to Publish</span>
            <% end %>
          <% elsif blog.state == 1 %>
            Published
          <% end %>
        </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/_doctors_data_table.html.erb
<%= content_for :head do %>
  <link rel="stylesheet" href="/vendor/datatables/media/css/jquery.dataTables.css">
  <link rel="stylesheet" href="/vendor/sweetalert/dist/sweetalert.css">
<% end %>

<div class="card bg-white">
          <div class="card-header">
            Students
          </div>
          <div class="card-block">
            <table class="table table-bordered table-striped datatable editable-datatable responsive align-middle bordered">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Contact</th>
                  <th>Roll No</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>

<%= content_for :foot do %>

<!-- page scripts -->
<script src="/vendor/datatables/media/js/jquery.dataTables.js"></script>
<script src="/vendor/sweetalert/dist/sweetalert.min.js"></script>
<!-- end page scripts -->
<!-- initialize page scripts -->
<script src="/scripts/helpers/bootstrap-datatables.js"></script>
<script src="/scripts/tables/students-table-edit.js"></script>
<!-- end initialize page scripts -->
<% end %>     

<div class="modal bs-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
   
  </div>

  <%= link_to "#", class: "fixed-new-button btn btn-info ", "data-toggle" =>"modal",  "data-target" => ".bs-modal-lg", remote: true do %>
    <i class="fa fa-plus"></i>
  <% end %>

app/views/admins/_medicine_edit_form.html.erb
<%= form_tag edit_medicine_data_admins_path(current_pharmacy)  ,role: "form",method: :post, id:"form", :multipart => true do %>

<%= hidden_field_tag :medicine_id, @medicine.id %>
           <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Edit Medicine</h4>
        </div>
        <div class="modal-body">
          <div class="container">
            <div class="row">
              <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Item Code</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :item_code, @medicine.item_code, class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
               <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Name</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :name, @medicine.name, class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Purchase Price</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :purchase_price, @medicine.purchase_price, class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
               <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Sale Price</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :price, @medicine.price, class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Manufacturer Name</label>
                    <div class="col-sm-3">
                      <%= text_field_tag :manufacturer_name, @medicine.manufacturer_name, class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-3">
                      <%= text_area_tag :description, @medicine.description, class: "form-control m-b" %> 
                    </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">State</label>
                    <div class="col-sm-3">
                      <%= select_tag 'state', options_for_select([['Inactive',0],['Active',1]], @medicine.state), class: "form-control cs-select", required: "" %>
                    </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                 <label  class="col-sm-2 control-label">Image</label>
                    <div class="col-sm-3">
                      <%= file_field_tag :image, class: "form-control m-b" %> 
                      <small> If you want to replace the previous image, please select a new one </small>
                    </div>
                </div>
              </div>
                        
            </div>
          </div>
        </div>
        <div class="modal-footer no-border">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
         <%= submit_tag "Submit",class:"btn btn-primary " %>
        </div>
      </div>
    </div>
          
          
<% end %>

app/views/admins/_procedures_table.html.erb
<div class="card bg-white">
  <div class="card-header">
    Procedures
  </div>
  <div class="card-block">
    <table class="table table-bordered table-striped datatable editable-datatable responsive align-middle bordered">
      <thead>
        <tr>
          <th>Title</th>
          <th>Details</th>
        </tr>
      </thead>
      <tbody>
      <% @procedures.each do |procedure| %>
      <tr>
        <td>
          <%= procedure.title %>
        </td>
        <td>
          <%= procedure.description %>
        </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

   

app/views/admins/_specialities_table.html.erb
<div class="card bg-white">
  <div class="card-header">
    Students
  </div>
  <div class="card-block">
    <table class="table table-bordered table-striped datatable editable-datatable responsive align-middle bordered">
      <thead>
        <tr>
          <th>Title</th>
          <th>Details</th>
        </tr>
      </thead>
      <tbody>
      <% @sepcialities.each do |sepciality| %>
      <tr>
        <td>
          <%= sepciality.title %>
        </td>
        <td>
          <%= sepciality.description %>
        </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

   

app/views/admins/blogs.html.erb
<% content_for :head do %>
  <%= render 'shared/header' %>
<% end %>
<%= render 'head_menu' %>

<%= render 'blogs' %>

<%= render 'shared/footer' %>

app/views/admins/cities.html.erb
<% content_for :head do %>
  <%= render 'shared/header' %>
<% end %>
<%= render 'head_menu' %>

<%= render 'cities' %>

<%= render 'shared/footer' %>

app/views/admins/conditions.html.erb
<% content_for :head do %>
  <%= render 'shared/header' %>
<% end %>
<%= render 'head_menu' %>

<%= render 'conditions' %>

<%= render 'shared/footer' %>

app/views/admins/medicines.html.erb
<% content_for :head do %>
  <%= render 'shared/header' %>
<% end %>
  <%= render 'head_menu' %>

 <div class="main-content">
        <div class="page-title">
          <div class="title">Medicines</div>
          <div class="sub-title">All Medicines stored in the database</div>
        </div>    
        <%= render 'medicines_data_table' %>
      </div>

<%= render 'shared/footer' %>
<%= hidden_field_tag 'medicines_path', '/api/get_medicines'%>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/new_hospital.js.erb
$(".bs-modal-lg").html("<%= escape_javascript(render(partial: "new_hospital_form")) %>");
  $(".bs-modal-lg").modal('show');

app/views/admins/new_speciality.js.erb
$(".bs-modal-lg").html("<%= escape_javascript(render(partial: "speciality_form")) %>");
  $(".bs-modal-lg").modal('show');

app/views/admins/procedures.html.erb
<% content_for :head do %>
  <%= render 'shared/header' %>
<% end %>
<%= render 'head_menu' %>

<%= render 'procedures' %>

<%= render 'shared/footer' %>