config/routes.rb
Rails.application.routes.draw do

  get 'public/sign_in'
  get 'public/home'
  get 'public/contact_us'
  get 'public/coming_soon'
  get 'public/doctors'
  get 'public/doctor_details'
  get 'zohoverify/verifyforzoho' => 'public#verifyforzoho'

  get 'public/search'
  post 'public/search_doctors'

  get 'public/open_appointment'
  post 'public/open_appointment'

  post 'public/login'

  get 'public/contact'
  get 'public/about'

  get 'public/doctor_registration'
  post 'public/register_doctor'
  
  post 'public/contact_form'
  post 'public/register_donor'
  post 'public/register_request_donation'
  post 'public/place_order'

  get 'public/privacy'
  get 'public/donor_registration'
  get 'public/request_donation'

  get 'public/healthy_living'
  get 'public/healthy_living/:id' => 'public#blog_details'

  get 'public/help'
  get 'public/show_location'
  get 'public/pharmacy'
  get 'public/add_medicine'
  get 'public/medicine_details'
  get 'public/checkout'

  get 'public/get_slots'

  get 'public/patient_registration'
  post 'public/register_patient'

  get 'public/appointment'
  post 'public/book_appointment'

  post 'public/search_medicine'

  get 'public/thank_you'

  get 'public/terms_and_conditions'

  get 'welcome/index'

  get 'welcome/about'
  get 'welcome/login'

  get 'welcome/help'

  get 'welcome/faqs'

  get 'welcome/contact_us'

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/help'

  get 'welcome/faqs'
  
  get 'api/get_patients'
  get 'api/get_appointments'
  get 'api/get_medicines'
  get 'api/get_orders'
  get 'api/get_stock'

  get 'api/verify_email'
  

  get 'admin' => "admins#dashboard"

  resources :pharmacies do
    collection do
      get 'login'
      get 'dashboard'
      get 'logout'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'orders'
      get 'set_status'

      get 'stock'
      get 'add_stock'
      post 'add_new_stock'
    end
  end

  resources :patients do 
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'appointments'
      get 'request_appointment'
      post 'create_new_appointment'

      get 'get_slots'

      get 'prescriptions'
      get 'prescription_details'
    end
  end

  resources :bloggers do
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'session_login'
    end
    member do
      get 'new_article'
      post 'create_new_article'
    end
  end

  resources :admins do 
    collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'procedures'
      get 'specialities'
      get 'conditions'
      get 'new_blood_group'
      get 'new_procedure'
      get 'new_condition'
      get 'destroy_session'
      get 'new_speciality'

      get 'hospitals'
      get 'cities'
      get 'new_hospital'
      get 'new_city'
      get 'donation_requests'
      get 'assign_donation_request'
      post 'assign_donor'

      get 'orders'
      get 'order_details'
      post 'assign_order'

      get 'new_blogger'
      post 'create_new_blogger'

      get 'medicines'
      get 'edit_medicine'
      get 'delete_medicine'
      post 'edit_medicine_data'

      get 'new_medicine'
      post 'create_new_medicine'
      get 'import_medicines'
      post 'import_medicines_data'

      get 'blogs'
      get 'publish_blog'
      get 'blog_content'

      post 'add_new_hospital'
      post 'add_new_city'
      post 'add_new_blood_group'
      post 'create_new_procedure'
      post 'create_new_speciality'
      post 'create_new_condition'
      post 'session_login'

      get 'edit_location'
      post 'edit_hospital_location'

      get 'pharmacies'

      get 'donors'
    end
  end

  resources :users do
     collection do
      get 'dashboard'
      post 'session_login'
    end
  end
  
resources :doctors do
     collection do
      get 'login'
      get 'logout'
      get 'dashboard'
      get 'destroy_session'
      post 'create_appointment' 
      post 'session_login'
    end
    member do
      get 'patients'
      get 'appointments'
      get 'via_n_appointments'
      get 'new_appointment'
      get 'new_stub_appointment'
      post 'add_new_stub_appointment'

      get 'availability_settings'
      post 'set_availability_details'
      get 'get_slots'

      get 'procedures'
      get 'add_procedure'
      post 'add_new_procedure'

      get 'conditions'
      get 'new_condition'
      post 'add_new_condition'

      get 'specialities'
      get 'add_speciality'
      post 'add_new_speciality'

      get 'prescriptions'
      get 'new_prescription'
      post 'add_new_prescription'
      get 'prescription_details'

      get 'settings'
      post 'update_information'

      get 'change_picture'
      post 'add_new_picture'

      get 'accept_appointment'
      get 'reject_appointment'

      get 'mark_paid'
      post 'mark_appointment_paid'
    end
  end

  root 'public#healthy_living'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :appointments
  has_many :patients
  has_many :doctor_specialities
  has_many :doctor_procedures
  has_many :doctor_conditions
  has_many :available_days
  has_many :slots
  has_many :prescriptions
  has_one :account, as: :owner
  has_one :document, as: :owner
  has_many :notifications, as: :owner
  self.per_page = 8
  def blocked?
    false
  end

  def get_image
    if document.present?
      return document.image
    else
      return get_default_image
    end
  end

  def get_default_image
    if gender == 1
      return '/images/male_doctor.png'
    else
      return '/images/female_doctor.png'
    end
  end

  def generate_empty_slots date
  	duration = slot_duration.to_i
  	day_detail = available_days.where(day: date.strftime('%A')).first
    
    if !day_detail.present?
      return []
    end

  	start = day_detail.start_time
  	empty_slots = []

  	while start <= day_detail.end_time - duration.minutes
  		empty_slots.push(start)
  		start = start + duration.minutes
   	end

   	allotted_slots = slots.select(:start_time).where(:start_time => date .. date.end_of_day)
    #raise exception if empty_slots has zero count
    allotted_slots_times = []
    for i in 0..allotted_slots.size-1
      allotted_slots_times.push(allotted_slots[i].start_time.to_datetime.to_s(:time))
    end
    for i in 0..empty_slots.size-1
      empty_slots[i] = empty_slots[i].to_datetime.to_s(:time)
    end
   	empty_slots = empty_slots - allotted_slots_times

   	return empty_slots
  end

  def get_specialities
    specialities = ""
    if !doctor_specialities.present?
      return "No Specialities Mentioned"
    end
    doctor_specialities[0..1].each do |d|
      specialities += d.speciality.title + ", "
    end
    specialities = specialities[0..-3]
    specialities += " ..."
     
  end
  
  def get_procedures
    procedures = ""
    if !doctor_procedures.present?
      return "No Procedures Mentioned"
    end
    doctor_procedures[0..1].each do |d|
      procedures += d.procedure.title + ", "
    end

    procedures = procedures[0..-3]
    procedures += " ..."
  end

  def get_conditions
    conditions = ""
    if !doctor_conditions.present?
      return "No Conditions Mentioned"
    end
    doctor_conditions[0..1].each do |d|
      conditions += d.condition.title + ", "
    end
    conditions = conditions[0..-3]
    conditions += " ..."
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate_doctor, except: [:login ,:session_login]
  before_action :update_notifications, except: [:login ,:session_login, :via_n_appointments]
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  require 'date'

  def add_new_condition
    for i in 0..params[:conditions].size-1
      current_doctor.doctor_conditions.create(doctor_id: current_doctor.id, condition_id: params[:conditions][i])
    end
    redirect_to :back
  end

  def new_condition
    @conditions = Condition.all
  end

  def conditions
    @conditions = current_doctor.doctor_conditions
  end

  def via_n_appointments
    unread = current_doctor.notifications.where(read: false, subject_type: 'Appointment').map(&:id)
    
    unread.each do |id|
      Notification.update(id, read: true)
    end
    render 'appointments'
  end

  def update_notifications
    @message = []
    @notifications = current_doctor.notifications.where(read: false, subject_type: 'Appointment').order(created_at: :desc)
    if @notifications.count != 0
      @message.push('You have ' + @notifications.count.to_s + ' new appointments.')
    end
    @notifications = current_doctor.notifications.where(read: false, subject_type: 'View').order(created_at: :desc)
    if @notifications.count != 0
      @message.push( @notifications.count.to_s + ' people viewed your profile. Total views: ' + current_doctor.views_count.to_s)
      @notifications.each do |n|
        Notification.update(n.id, read: true)
      end
    end
  end

  def update_information
    Doctor.update(current_doctor.id, bio: params[:bio], experience: params[:experience], education: params[:education], title_education: params[:title_education])
    flash[:success] = "Information updated successfully"
    redirect_to :back
  end

  def mark_appointment_paid
    Tranzaction.update(params[:tranzaction_id], note: params[:note], paid: true)
    redirect_to :back
  end

  def mark_paid
    @tranzaction = Appointment.find(params[:appointment_id]).tranzaction

  end

  def accept_appointment
    Appointment.update(params[:appointment_id], state: 1)
    redirect_to :back
  end

  def reject_appointment
    Appointment.update(params[:appointment_id], state: 2)
    redirect_to :back
  end

  def dashboard
    
  end

  def add_new_picture
    if current_doctor.document.present?
      current_doctor.document.update(image: params[:image])
    else
      current_doctor.create_document(image: params[:image])
    end
    redirect_to :back
  end

  def change_picture

  end

  def settings

  end

  def prescription_details
    medicine_ids = Prescription.find(params[:prescription_id]).prescription_items.select("medicine_id")
    @medicines = []
    medicine_ids.each do |medicine|
      @medicines.push(Medicine.find(medicine.medicine_id))
    end
    @prescription = Prescription.find(params[:prescription_id])
  end

  def prescriptions
    @prescriptions = current_doctor.prescriptions
  end

  def new_prescription
    @patients = Patient.all
    @medicines = Medicine.all
  end

  def add_new_prescription
    prescription = current_doctor.prescriptions.create(patient_id: params[:patient], note: params[:note])

    for i in 0..params[:medicines].size-1
      prescription.prescription_items.create(medicine_id: params[:medicines][i])
    end

    flash[:success_prescription] = "Prescription Added Successfully"
    redirect_to :back
  end

  def get_slots
    date = params[:date]
    if !date.present?
      respond_to do |format|
         format.json { render :json => @empty_slots }
      end
      return
    end
    date = Date.strptime(date, "%m/%d/%Y")
    date = date.to_datetime
    
    #current_doctor.verify_day date --verifies if the doctor has set available for the given day

    slots = current_doctor.slots.where(:start_time => date .. date.end_of_day)
    @empty_slots = current_doctor.generate_empty_slots date
    
    respond_to do |format|
       format.json { render :json => @empty_slots }
    end
  end

  def availability_settings
    @days = current_doctor.available_days
    @duration = current_doctor.slot_duration

  end

  def set_availability_details

    if (params[:duration].present?)
      Doctor.update(current_doctor.id, slot_duration: params[:duration])
    end
    if params[:amount].present?
      Doctor.update(current_doctor.id, appointment_fee: params[:amount])
    end
    if params[:mon].present?
      day = current_doctor.available_days.where(day: "Monday").first 
      if !day.present?
        day = current_doctor.available_days.create(day: "Monday")
      end
      day.set_start_time params[:mon_start_time]
      day.set_end_time params[:mon_end_time]
    else
      day = current_doctor.available_days.where(day: "Monday").first
      if day.present?
        day.delete
      end 
    end
    if params[:tue].present?
      day = current_doctor.available_days.where(day: "Tuesday").first 
      if !day.present?
        day = current_doctor.available_days.create(day: "Tuesday")
      end

      day.set_start_time params[:tue_start_time]
      day.set_end_time params[:tue_end_time]
    else
      day = current_doctor.available_days.where(day: "Tuesday").first
      if day.present?
        day.delete
      end 

    end
    if params[:wed].present?
      day = current_doctor.available_days.where(day: "Wednesday").first 
      if !day.present?
        day = current_doctor.available_days.create(day: "Wednesday")
      end
      day.set_start_time params[:wed_start_time]
      day.set_end_time params[:wed_end_time]
    else
      day = current_doctor.available_days.where(day: "Wednesday").first
      if day.present?
        day.delete
      end 
    end
    if params[:thur].present?
      day = current_doctor.available_days.where(day: "Thursday").first 
      if !day.present?
        day = current_doctor.available_days.create(day: "Thursday")
      end
      day.set_start_time params[:thur_start_time]
      day.set_end_time params[:thur_end_time]
    else
      day = current_doctor.available_days.where(day: "Thursday").first
      if day.present?
        day.delete
      end 
    end
    if params[:fri].present?
      day = current_doctor.available_days.where(day: "Friday").first 
      if !day.present?
        day = current_doctor.available_days.create(day: "Friday")
      end
      day.set_start_time params[:fri_start_time]
      day.set_end_time params[:fri_end_time]
    else
      day = current_doctor.available_days.where(day: "Friday").first
      if day.present?
        day.delete
      end 
    end
    if params[:sat].present?
      day = current_doctor.available_days.where(day: "Saturday").first 
      if !day.present?
        day = current_doctor.available_days.create(day: "Saturday")
      end
      day.set_start_time params[:sat_start_time]
      day.set_end_time params[:sat_end_time]
    else
      day = current_doctor.available_days.where(day: "Saturday").first
      if day.present?
        day.delete
      end 
    end
    if params[:sun].present?
      day = current_doctor.available_days.where(day: "Sunday").first 
      if !day.present?
        day = current_doctor.available_days.create(day: "Sunday")
      end
      day.set_start_time params[:sun_start_time]
      day.set_end_time params[:sun_end_time]
    else
      day = current_doctor.available_days.where(day: "Sunday").first
      if day.present?
        day.delete
      end 

    end
    redirect_to :back
  end

  def specialities
    doctor_specialities = current_doctor.doctor_specialities 
    @specialities = []
    if doctor_specialities.present?
      doctor_specialities.each do |doctor_speciality|
        @specialities.push(Speciality.find(doctor_speciality.speciality_id))
      end
    end
  end

  def add_speciality
    #send those specialities that hasn't been added by the doctor
    @specialities = Speciality.all
  end

  def add_new_speciality
    current_doctor.doctor_specialities.create(doctor_id: current_doctor.id, speciality_id: params[:specialities])
    redirect_to :back
  end

  def procedures
    doctor_procedures = current_doctor.doctor_procedures 
    @procedures = []
    
    if doctor_procedures.present?
      doctor_procedures.each do |doctor_procedure|
        @procedures.push(Procedure.find(doctor_procedure.procedure_id))
      end
    end
  end

  def add_procedure
    #send those procedures that hasn't been added by the doctor
    @procedures = Procedure.all
  end

  def add_new_procedure
    params[:procedures].each do |id|
      current_doctor.doctor_procedures.create(doctor_id: current_doctor.id, procedure_id: id)
    end
    redirect_to :back
  end

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end



  def appointments
  end
  
  def new_appointment
    @appointment = Appointment.new
  end

  def new_stub_appointment

  end

  def add_new_stub_appointment
    
    for i in 0..params[:selected_slots].size-1
      date_time = Date.strptime(params[:appointment_date], "%m/%d/%Y").to_datetime + Time.parse(params[:selected_slots][i]).seconds_since_midnight.seconds
      current_doctor.slots.create(start_time: date_time, stub: true)
    end
    flash[:success_appointment] = "Slots marked busy!"
    redirect_to :back
  end
  
  def create_appointment
    date_time = Date.strptime(params[:appointment_date], "%m/%d/%Y").to_datetime + Time.parse(params[:selected_slot]).seconds_since_midnight.seconds
    appointment = current_doctor.appointments.create(patient_id: params[:patient], state: 1)
    appointment.create_slot(doctor_id: current_doctor.id, start_time: date_time)
    appointment.notify_the_admin
    flash[:success_appointment] = "Appointment Created for " + Patient.find(params[:patient]).name + "!"
    redirect_to :back
  end
  
  def login
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit

app/helpers/doctors_helper.rb
module DoctorsHelper
  
end

app/views/doctors/_dashboard.html.erb
<!-- main area -->
       <div class="main-content">
        <div class="page-title">
          <div class="title">Dashboard</div>
        </div>  
        <h3>Deal with Patients </h3>  
        <div class="row">
          <div class="col-sm-6">
            <div class="card card-block bg-white">
              <h4 class="card-title">Patients</h4>
              <% if flash[:success].present? %> 
                <div class="alert alert-success">
                  <%= flash[:success] %>
                </div>
              <% elsif flash[:error].present? %>
                <div class="alert alert-error">
                  <%= flash[:error] %>
                </div>
              <% end %>
              <p class="card-text" id="teacher_box">
                <br/>
                <%= link_to new_patient_path,  class: "btn btn-primary ",  remote: true do %>
                            <i class="fa fa-eye"></i> Add new Patient
                <% end %>

              </p>                              
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card card-block bg-white">
              <h4 class="card-title">Presciption</h4>
              <% if flash[:success_prescription].present? %> 
                <div class="alert alert-success">
                  <%= flash[:success_prescription] %>
                </div>
              <% elsif flash[:error_prescription].present? %>
                <div class="alert alert-error">
                  <%= flash[:error_prescription] %>
                </div>
              <% end %>
              <p class="card-text" id="teacher_box">
                <br/>
                <%= link_to new_prescription_doctor_path(current_doctor),  class: "btn btn-primary ",  remote: true do %>
                            <i class="fa fa-eye"></i> Add new Prescription
                <% end %>

              </p>                              
            </div>
          </div>
        </div>
        <h3>Manage your appointments </h3>  
        <div class="row">
          <div class="col-sm-6">
            <div class="card card-block bg-white">
              <h4 class="card-title">Make Appointments or Mark Unavailability</h4>
              <% if flash[:success_appointment].present? %> 
                <div class="alert alert-success">
                  <%= flash[:success_appointment] %>
                </div>
              <% elsif flash[:error_appointment].present? %>
                <div class="alert alert-error">
                  <%= flash[:error_appointment] %>
                </div>
              <% end %>
              <p class="card-text" id="teacher_box">
                <br/>
                <%= link_to new_appointment_doctor_path(current_doctor), class: "btn btn-primary ", "data-toggle" =>"modal",  "data-target" => ".bs-modal-lg", remote: true do %>
                  <i class="fa fa-plus"></i> Add new Appointment
                <% end %> 
                <br /> <br />
                <%= link_to appointments_doctor_path(current_doctor), class: "btn btn-primary " do %>
                  <i class="fa fa-plus"></i> See All Appointments
                <% end %>
                <br /> <br />
                <%= link_to new_stub_appointment_doctor_path(current_doctor), class: "btn btn-primary ", "data-toggle" =>"modal",  "data-target" => ".bs-modal-lg", remote: true do %>
                  <i class="fa fa-plus"></i> Mark Slots Unavailable
                <% end %>
              </p>                              
            </div>
          </div>
          <div class="col-sm-6">
            <div class="card card-block bg-white">
              <h4 class="card-title">Appointment Settings</h4>
              <p class="card-text" id="teacher_box">
                <br/>
                <%= link_to availability_settings_doctor_path(current_doctor),  class: "btn btn-primary",  remote: true do %>
                            <i class="fa fa-eye"></i> Set Availability Details
                <% end %>
              </p>                              
            </div>
          </div>
        </div>
        <h3>Edit your Profile</h3>  
        <div class="row">
          <div class="col-sm-6">
            <div class="card card-block bg-white">
              <h4 class="card-title">Add New Speciality</h4>
              <% if flash[:success_speciality].present? %> 
                <div class="alert alert-success">
                  <%= flash[:success_speciality] %>
                </div>
              <% end %>
              <p class="card-text" id="teacher_box">
                <%= link_to specialities_doctor_path(current_doctor) do %>
                    <strong>Show my Specialities</strong>
                <% end %>
                <br/><br/>
                 <%= link_to add_speciality_doctor_path(current_doctor), class: "btn btn-primary ", remote: true do %>
                            <i class="fa fa-eye"></i> Add new Speciality
                <% end %>
              </p>
            </div>
          </div>
        </div>
      <!-- /main area -->
      
  <div class="modal bs-modal-lg" tabindex="-1" role="dialog" aria-hidden="true"></div>

  <script type="text/javascript">

      function getFreeSlots(id){
        var date = document.getElementById("magic_date").value;
        if (date == null || date == ""){
          generateError("Please Select a Date First");
          return; 
        }
        else{
          getSlots(id);
        }
      }
      function getSlots(id){
        var data = document.getElementById("magic_date").value;
        var path = "/public/get_slots?date="+data+"&doctor_id="+id;
        jQuery.ajax({url: path,
         dataType: 'json',
         success: function(result){
          console.log(result)
          evaluate(result);
        }});
      }

      function evaluate(result){
        var html;

        if (result == null || result.length == 0){
          generateError(null);
          return;
        }
        html = "<select id='slots_select' multiple required='required' name='selected_slot' style='width: 279px;' class='form-control'>";
        for (i = 0; i < result.length; i++){
          var temp = "<option value='" + result[i] + "'>" + result[i] + "</option>";
          html += temp;
        }
        html += "</select>";
        document.getElementById("empty_slots").innerHTML = html;
        jQuery('#slots_select').popSelect({
          showTitle: false,
          placeholderText: 'Click to Select your appointment slot',
          position: 'bottom',
          maxAllowed: 1
        });
      }
      function generateError(message){
        console.log(message);
        if (message == null){
          var html = "<div class='alert alert-danger'><strong>Oops! </strong> The doctor has no available slots on the selected day.</div>";
        }
        else{
          var html = "<div class='alert alert-danger'><strong>Oops! </strong>" + message + "</div>"; 
        }
        document.getElementById("empty_slots").innerHTML = html;
      }
    </script>

app/views/doctors/_doctor_login_form.html.erb
 <div class="app signin v2 usersession">
    <div class="session-wrapper">
    <div class="session-carousel slide" data-ride="carousel" data-interval="300">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
          <div class="item active" style="background-image:url(/images/bg1.jpg);background-size:cover;background-repeat: no-repeat;background-position: 50% 50%;">
          <div class="item" style="background-image:url(/images/bg2.jpg);background-size:cover;background-repeat: no-repeat;background-position: 50% 50%;">
          </div>
        </div>
      </div>
            </div>
      <div class="card bg-white no-border">
        <div class="card-block">
           <%= form_tag session_login_doctors_path, method: "POST" do %>
        
            <div class="text-center m-b">
              <h4 class="text-uppercase">Welcome back</h4>
              <p>Please sign in to your account</p>
            </div>
            <div class="form-inputs p-b">
             <div class="form-group m-b">
              <%= label_tag :email ,:email , class: "text-uppercase" %>
              <%= text_field_tag "email", "",autofocus: true, class: "form-control input-lg", placeholder: "Email", required: "" %>
              <div class="help-block with-errors"></div>
            </div>
             <div class="form-group m-b">
            <%= label_tag :password,:password, class: "text-uppercase" %>
            <%= password_field_tag "password", "", autocomplete: "off", class: "form-control  input-lg", placeholder: "Password", "data-minlength" => "8" , required: ""  %>
            <div class="help-block with-errors"></div>
          </div>
          
          <div class="checkbox">
            <label>
              <%= check_box_tag :remember_me , false%> 
              Remember Me
            </label>
          </div>
                
            </div>
             <%= submit_tag "Log in", class: "btn btn-primary btn-block btn-lg m-b" %>
             <% end %>
        </div>
      </div>
      <div class="push"></div>
    </div>
  </div>

app/views/doctors/_patients_data_table.html.erb
<%= content_for :head do %>
  <link rel="stylesheet" href="/vendor/datatables/media/css/jquery.dataTables.css">
  <link rel="stylesheet" href="/vendor/sweetalert/dist/sweetalert.css">
<% end %>

<div class="card bg-white">
          <div class="card-header">
            Students
          </div>
          <div class="card-block">
            <table class="table table-bordered table-striped datatable editable-datatable responsive align-middle bordered">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Contact</th>
                  <th>Roll No</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>

<%= content_for :foot do %>

<!-- page scripts -->
<script src="/vendor/datatables/media/js/jquery.dataTables.js"></script>
<script src="/vendor/sweetalert/dist/sweetalert.min.js"></script>
<!-- end page scripts -->
<!-- initialize page scripts -->
<script src="/scripts/helpers/bootstrap-datatables.js"></script>
<script src="/scripts/tables/patients-table-edit.js"></script>
<!-- end initialize page scripts -->
<% end %>     

<div class="modal bs-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
   
   
  </div>
  <%= link_to new_patient_path, class: "fixed-new-button btn btn-info ", "data-toggle" =>"modal",  "data-target" => ".bs-modal-lg", remote: true do %>
    <i class="fa fa-plus"></i>
  <% end %>

app/views/doctors/_settings.html.erb
<div class="main-content">
  <div class="page-title">
    <div class="title">Profile Settings</div>
    
  </div>
  <div class="row">
  	<div class="col-md-12">
  		<% if flash[:success].present? %>
  			<div class="alert alert-success"><%= flash[:success] %></div>
  		<% end %>
  	</div>
  </div>

  <div class="card bg-white">
    <div class="card-header text-lg-center">
      Manage your profile
    </div>
    <div class="card-block">
      <div class="row m-a-0">
        <div class="col-lg-6">
          <%= form_tag update_information_doctor_path(current_doctor), class:"form-horizontal", role: "form", method: :post, id:"form", "autocomplete" => "off", :multipart => true do %>
            <div class="form-group">
              <label class="col-sm-2 control-label">Specialization</label>
              <div class="col-sm-8">
                <%= text_field_tag :title_education, current_doctor.title_education, "placeholder" => "For eg. Dentist, Psychiatrist etc. This will be displayed right below your name on your profile page.", class: "form-control m-b" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Bio</label>
              <div class="col-sm-8">
                <%= text_area_tag :bio, current_doctor.bio, "placeholder" => "Enter your Bio (max 100 words). This information will be displayed on your public profile.", class: "form-control m-b", "rows" => "5" %> 
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Education</label>
              <div class="col-sm-8">
                <%= text_area_tag :education, current_doctor.education, "placeholder" => "Share your Education History. This information will be displayed on your public profile.", class: "form-control m-b", "rows" => "5" %>
              </div>
            </div>
            
            <div class="form-group">
              <label class="col-sm-2 control-label">Experience</label>
              <div class="col-sm-8">
                <%= text_area_tag :experience, current_doctor.experience, "placeholder" => "Share your past experience. This information will be displayed on your public profile.", class: "form-control m-b", "rows" => "5" %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-10 text-lg-right">
                <%= submit_tag "Update Information",class:"btn btn-primary " %>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-lg-6">
          <div class="card card-block bg-white">
              <h4 class="card-title">Update Profile Picture</h4>
              <p class="card-text" id="teacher_box">
                <br/>
                <%= link_to change_picture_doctor_path(current_doctor),  class: "btn btn-primary",  remote: true do %>
                            <i class="fa fa-eye"></i> Change Picture
                <% end %>
              </p>                              
            </div>
        </div>
      </div>
    </div>
  </div>
  
</div>
<div class="modal bs-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
</div>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>